### ISSUE TITLE
Profile Challenge

### ISSUE THREAD

**Issue by bearnard** [bearnard/prime_challenge#2]
The profile challenge consists of two tasks.

This issue will track the progress of each:
- [x] Create a script to generate prime numbers up to n: https://github.com/bearnard/prime_challenge/pull/1
- [x] Write a program that takes the python file above, executes it and profiles it. We are looking for a way to analyze the code’s: time of completion, spent on each line or function, and lines executed as well as missed. https://github.com/bearnard/prime_challenge/pull/4

Assumptions:
We will use python 2.7

Missing:
Tests: We could add a test that compares a known working algorithm with ours, but it feels a bit silly with primes. (infinity etc)

Improvements:
- [x] Generate the primes using a more efficient algorithm: Sieve of Eratosthenes perhaps... https://github.com/bearnard/prime_challenge/blob/f6a25b6c8d6444f9213ede833a9bd8cf5cd0f138/gen_primes_erato.py

@chrisgeo

**Comment by bearnard** [comment]
I'll attempt to make use of line_profiler to profile the prime script: https://github.com/rkern/line_profiler

**Comment by bearnard** [comment]
@chrisgeo 

line_profiler has kernprof which does what we want.

```

 kernprof -l -v gen_primes.py 1000
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569, 571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643, 647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727, 733, 739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823, 827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911, 919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997]
Wrote profile results to gen_primes.py.lprof
Timer unit: 1e-06 s

Total time: 0.401521 s
File: gen_primes.py
Function: prime_list at line 4

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
     4                                           @profile
     5                                           def prime_list(num):
     6
     7         1            2      2.0      0.0      primes = []
     8      1000          394      0.4      0.1      for x in xrange(2, num + 1):
     9       999          445      0.4      0.1          is_prime = True
    10    499500       183705      0.4     45.8          for y in xrange(2, x):
    11    498501       214225      0.4     53.4              if x % y == 0:  # if y is a factor of x
    12      5070         2151      0.4      0.5                  is_prime = False
    13       999          417      0.4      0.1          if is_prime:
    14       168          181      1.1      0.0              primes.append(x)
    15         1            1      1.0      0.0      return primes

```

I'm also attempting to write our own one using: https://github.com/bearnard/prime_challenge/commit/e6c92e943e3e73ecce5f5ebfce7c83e2ab0788d7

But not winning with it yet.

**Comment by chrisgeo** [comment]
I like the progress so far @bearnard. I hadn't through of using kernprof before.

**Comment by bearnard** [comment]
@chrisgeo 

I've opened 2 pulls: https://github.com/bearnard/prime_challenge/pull/1 and https://github.com/bearnard/prime_challenge/pull/3

**Comment by chrisgeo** [comment]
My apologies @bearnard . Thanks for the PRs. I'll take a quick look.

**Comment by bearnard** [comment]
@chrisgeo 

All the tasks have been completed.

Thanks for the feedback.
I enjoyed this challenge.
